create table "CB_AI_MODELS" (
   "ID"             number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for an AI model connection configuration.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "NAME"           varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Display name for selecting this model configuration in APEX.'
   ,"DISPLAY" 'Name' ),
   "SIGNATURE_TYPE" varchar2(30 char) not null enable annotations ( "DESCRIPTION" 'Provider signature family passed to CB_AGENT, such as OPENAI_COMPATIBLE or ANTHROPIC.'
   ,"DISPLAY" 'Signature Type' ),
   "URL"            varchar2(4000 char) not null enable annotations ( "DESCRIPTION" 'Provider endpoint URL.'
   ,"DISPLAY" 'URL' ),
   "API_KEY"        varchar2(4000 char) not null enable annotations ( "DESCRIPTION" 'Raw provider API secret. CB_AGENT formats provider-specific request headers at runtime.'
   ,"DISPLAY" 'API Key' ),
   "MODEL"          varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Provider model identifier.'
   ,"DISPLAY" 'Model' ),
   "MAX_TOKENS"     number annotations ( "DESCRIPTION" 'Optional default maximum response tokens for this model configuration.'
   ,"DISPLAY" 'Max Tokens' ),
   "SORT_ORDER"     number default 99 not null enable annotations ( "DESCRIPTION" 'Display order for this model configuration in chat option lists.'
   ,"DISPLAY" 'Sort Order' ),
   "EXCLUDE_FROM_CHAT_OPTION" varchar2(1 char) default 'N' not null enable annotations ( "DESCRIPTION" 'Whether to exclude this model configuration from chat option lists (Y/N).'
   ,"DISPLAY" 'Exclude From Chat Option' ),
   "CREATED"        date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the model configuration was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_AI_MODELS_ID_PK" primary key ( "ID" )
      using index enable,
   constraint "CB_AI_MODELS_NAME_UNQ" unique ( "NAME" )
      using index enable,
   constraint "CB_AI_MODELS_MAX_TOKENS_CK"
      check ( max_tokens is null or max_tokens > 0 ) enable,
   constraint "CB_AI_MODELS_EXCL_CHAT_OPT_CK"
      check ( exclude_from_chat_option in ( 'Y', 'N' ) ) enable
) annotations ( "DESCRIPTION" 'Stores AI model connection configurations used by CB_AGENT.',"DISPLAY" 'AI Models' );
