create table "CB_CHATBOT_CONVERSATIONS" (
   "ID"              number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for a conversation message row.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "CHATBOT_ID"      number
      annotations ( "DESCRIPTION" 'Chatbot that owns this conversation message.',"DISPLAY" 'Chatbot ID',"FOREIGNKEY" ),
   "ROLE"            varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Participant role for the message, such as user, assistant, or system.'
   ,"DISPLAY" 'Role' ),
   "MESSAGE"         varchar2(4000 char)
      annotations ( "DESCRIPTION" 'Message text stored for the conversation.',"DISPLAY" 'Message' ),
   "MESSAGE_EMBEDDING" vector
      annotations ( "DESCRIPTION" 'Embedding associated with the message for conversation memory recall.',"DISPLAY" 'Message Embedding' ),
   "IS_SUMMARIZED"   varchar2(1 char) default on null 'N' not null enable annotations ( "DESCRIPTION" 'Indicates whether this message has been included in the chatbot running summary.'
   ,"DISPLAY" 'Is Summarized' ),
   "SUMMARIZED_DATE" date
      annotations ( "DESCRIPTION" 'Date when this message was included in the chatbot running summary.',"DISPLAY" 'Summarized Date'
      ),
   "CREATED"         date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the conversation message was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_CHATBOT_CONVERSATIONS_IS_SUM_CK"
      check ( is_summarized in ( 'Y',
                                 'N' ) ) enable,
   constraint "CB_CHATBOT_CONVERSATIONS_ID_PK" primary key ( "ID" )
      using index enable
) annotations ( "DESCRIPTION" 'Stores chatbot conversation messages and related embedding data.',"DISPLAY" 'Chatbot Conversations'
);

alter table "CB_CHATBOT_CONVERSATIONS"
   add constraint "CB_CHATBOT_CONVERSATIONS_CHATBOT_ID_FK"
      foreign key ( "CHATBOT_ID" )
         references "CB_CHATBOTS" ( "ID" )
      enable;

create index "CB_CHATBOT_CONVERSATIONS_I2" on
   "CB_CHATBOT_CONVERSATIONS" (
      "CHATBOT_ID",
      "IS_SUMMARIZED",
      "ID"
   );

create index "CB_CHATBOT_CONVERSATIONS_I1" on
   "CB_CHATBOT_CONVERSATIONS" (
      "CHATBOT_ID"
   );
