create table "CB_CHATBOT_IMAGES" (
   "ID"              number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for a chatbot image.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "CHATBOT_ID"      number not null enable annotations ( "DESCRIPTION" 'Chatbot that owns this image.'
   ,"DISPLAY" 'Chatbot ID',"FOREIGNKEY" ),
   "IMAGE"           blob not null enable
      annotations ( "DESCRIPTION" 'Image content associated with the chatbot or its searchable products.',"DISPLAY" 'Image' ),
   "IMAGE_DEFINITION"           varchar2(300 char)
      annotations ( "DESCRIPTION" 'Text definition of the image used for display and semantic search context.',"DISPLAY" 'Image Definition' ),
   "IMAGE_DEFINITION_EMBEDDING" vector(384, float32)
      annotations ( "DESCRIPTION" 'Embedding associated with the image definition for semantic image search.',"DISPLAY" 'Image Definition Embedding' ),
   "MIME_TYPE"       varchar2(100 char) not null enable annotations ( "DESCRIPTION" 'MIME type for the stored image.'
   ,"DISPLAY" 'MIME Type' ),
   "FILENAME"        varchar2(255 char)
      annotations ( "DESCRIPTION" 'Original filename for the stored image.',"DISPLAY" 'Filename' ),
   "CREATED"         date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the image was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_CHATBOT_IMAGES_ID_PK" primary key ( "ID" )
      using index enable
) annotations ( "DESCRIPTION" 'Stores chatbot-owned images, image definitions, and definition embeddings for searchable product context.',"DISPLAY" 'Chatbot Images'
);

alter table "CB_CHATBOT_IMAGES"
   add constraint "CB_CHATBOT_IMAGES_CHATBOT_FK"
      foreign key ( "CHATBOT_ID" )
         references "CB_CHATBOTS" ( "ID" )
         on delete cascade
      enable;

create index "CB_CHATBOT_IMAGES_I1" on
   "CB_CHATBOT_IMAGES" (
      "CHATBOT_ID"
   );
