create table "CB_CHATBOT_ARCHIVES" (
   "ID"            number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for an archived chatbot conversation.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "CHATBOT_ID"    number
      annotations ( "DESCRIPTION" 'Identifier of the chatbot that owned the archived conversation. No foreign key is retained so archive history survives chatbot deletion.'
      ,"DISPLAY" 'Chatbot ID' ),
   "MESSAGES"      clob not null enable
      annotations ( "DESCRIPTION" 'JSON array containing the complete archived conversation transcript in message order.'
      ,"DISPLAY" 'Messages' ),
   "CREATED"       date default on null sysdate not null enable
      annotations ( "DESCRIPTION" 'Date when the conversation was archived.'
      ,"DISPLAY" 'Archived' ),
   "SYSTEM_PROMPT" clob
      annotations ( "DESCRIPTION" 'Snapshot of the chatbot system prompt at archive time.'
      ,"DISPLAY" 'System Prompt' ),
   "BOT_NAME"      varchar2(4000 char)
      annotations ( "DESCRIPTION" 'Snapshot of the chatbot name at archive time.'
      ,"DISPLAY" 'Bot Name' ),
   constraint "CB_CHATBOT_ARCHIVES_ID_PK" primary key ( "ID" )
      using index enable
) annotations ( "DESCRIPTION" 'Stores one complete archived conversation per row, with chatbot metadata snapshots.',"DISPLAY" 'Chatbot Archives' );