create table "CB_CHATBOT_TOOLS" (
   "ID"         number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for a chatbot tool assignment.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "CHATBOT_ID" number not null enable annotations ( "DESCRIPTION" 'Chatbot that may use the tool.'
   ,"DISPLAY" 'Chatbot ID',"FOREIGNKEY" ),
   "TOOL_ID"    number not null enable annotations ( "DESCRIPTION" 'Reusable tool enabled for the chatbot.'
   ,"DISPLAY" 'Tool ID',"FOREIGNKEY" ),
   "ENABLED_YN" varchar2(1 char) default on null 'Y' not null enable annotations ( "DESCRIPTION" 'Per-chatbot tool enablement flag.'
   ,"DISPLAY" 'Enabled' ),
   "CREATED"    date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the tool was assigned to the chatbot.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_CHATBOT_TOOLS_ID_PK" primary key ( "ID" )
      using index enable,
   constraint "CB_CHATBOT_TOOLS_UNQ" unique ( "CHATBOT_ID",
                                             "TOOL_ID" )
      using index enable,
   constraint "CB_CHATBOT_TOOLS_ENABLED_CK"
      check ( enabled_yn in ( 'Y',
                              'N' ) ) enable
) annotations ( "DESCRIPTION" 'Maps enabled agent tools to chatbots.',"DISPLAY" 'Chatbot Tools' );

alter table "CB_CHATBOT_TOOLS"
   add constraint "CB_CHATBOT_TOOLS_CHATBOT_FK"
      foreign key ( "CHATBOT_ID" )
         references "CB_CHATBOTS" ( "ID" )
      enable;

alter table "CB_CHATBOT_TOOLS"
   add constraint "CB_CHATBOT_TOOLS_TOOL_FK"
      foreign key ( "TOOL_ID" )
         references "CB_TOOLS" ( "ID" )
      enable;

create index "CB_CHATBOT_TOOLS_I1" on
   "CB_CHATBOT_TOOLS" (
      "CHATBOT_ID",
      "ENABLED_YN"
   );

