create table "CB_CHATBOTS" (
   "ID"              number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for a chatbot definition.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "NAME"            varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Unique chatbot name shown to administrators or users.'
   ,"DISPLAY" 'Name' ),
   "IMAGE"           blob
      annotations ( "DESCRIPTION" 'Optional display image or thumbnail for the chatbot.',"DISPLAY" 'Image' ),
   "IMAGE_MIME_TYPE" varchar2(100 char)
      annotations ( "DESCRIPTION" 'MIME type for the chatbot display image.',"DISPLAY" 'Image MIME Type' ),
   "IMAGE_FILENAME"  varchar2(255 char)
      annotations ( "DESCRIPTION" 'Original filename for the chatbot display image.',"DISPLAY" 'Image Filename' ),
   "PROMPT"          clob
      annotations ( "DESCRIPTION" 'Primary system or instruction prompt for the chatbot.',"DISPLAY" 'Prompt' ),
   "WELCOME_MESSAGE" clob
      annotations ( "DESCRIPTION" 'Initial message shown when a user starts a chat.',"DISPLAY" 'Welcome Message' ),
   "SUMMARY_PROMPT"  clob
      annotations ( "DESCRIPTION" 'Prompt used to summarize chatbot conversation context.',"DISPLAY" 'Summary Prompt' ),
   "CURRENT_SUMMARY" clob
      annotations ( "DESCRIPTION" 'Current stored summary for the chatbot.',"DISPLAY" 'Current Summary' ),
   "GLOBAL_CONTEXT" clob
      annotations ( "DESCRIPTION" 'Additional context to prepend into the conversation. Separated from PROMPT to avoid injecting directly into it',"DISPLAY" 'Global Context' ),
   "IMAGE_SELECTION_MODEL_ID" number
      annotations ( "DESCRIPTION" 'Optional AI model configuration used to extract the primary image-search term from a completed chat turn.',"DISPLAY" 'Image Selection Model' ),
   "IMAGE_SELECTION_PROMPT" clob
      annotations ( "DESCRIPTION" 'Instructions for extracting a concise primary-product phrase for image selection.',"DISPLAY" 'Image Selection Prompt' ),
   "CREATED"         date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the chatbot definition was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_CHATBOTS_ID_PK" primary key ( "ID" )
      using index enable,
   constraint "CHATBOTS_NAME_UNQ" unique ( "NAME" )
      using index enable
) annotations ( "DESCRIPTION" 'Stores chatbot definitions, display image metadata, and prompt configuration.',"DISPLAY" 'Chatbots' );

alter table "CB_CHATBOTS"
   add constraint "CB_CHATBOTS_IMG_SEL_MODEL_FK"
      foreign key ( "IMAGE_SELECTION_MODEL_ID" )
         references "CB_AI_MODELS" ( "ID" )
         on delete set null
      enable;
