create table "CB_TOOLS" (
   "ID"               number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for an agent tool definition.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "TOOL_NAME"        varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Stable tool name exposed to the LLM, such as contextual_memory.'
   ,"DISPLAY" 'Tool Name' ),
   "DESCRIPTION"      clob not null enable
      annotations ( "DESCRIPTION" 'LLM-facing description of when and how to use this tool.',"DISPLAY" 'Description' ),
   "TOOL_TYPE"        varchar2(50 char) default on null 'CONTEXTUAL_MEMORY' not null enable annotations ( "DESCRIPTION" 'Internal tool executor type.'
   ,"DISPLAY" 'Tool Type' ),
   "ENABLED_YN"       varchar2(1 char) default on null 'Y' not null enable annotations ( "DESCRIPTION" 'Global tool enablement flag.'
   ,"DISPLAY" 'Enabled' ),
   "MAX_ROWS"         number default on null 1000 not null enable annotations ( "DESCRIPTION" 'Maximum number of rows/messages the tool may inspect or return before result-size clipping.'
   ,"DISPLAY" 'Max Rows' ),
   "MAX_RESULT_CHARS" number default on null 100000 not null enable annotations ( "DESCRIPTION" 'Maximum character count returned by the tool before clipping.'
   ,"DISPLAY" 'Max Result Chars' ),
   "CREATED"          date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the tool definition was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_TOOLS_ID_PK" primary key ( "ID" )
      using index enable,
   constraint "CB_TOOLS_NAME_UNQ" unique ( "TOOL_NAME" )
      using index enable,
   constraint "CB_TOOLS_ENABLED_CK"
      check ( enabled_yn in ( 'Y',
                              'N' ) ) enable,
   constraint "CB_TOOLS_MAX_ROWS_CK"
      check ( max_rows > 0 ) enable,
   constraint "CB_TOOLS_MAX_RESULT_CHARS_CK"
      check ( max_result_chars > 0 ) enable
) annotations ( "DESCRIPTION" 'Stores reusable agent tool definitions.',"DISPLAY" 'Tools' );

