create table "CB_TOOLS" (
   "ID"               number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale not null enable annotations ( "DESCRIPTION" 'Surrogate primary key for an agent tool definition.'
   ,"DISPLAY" 'ID',"PRIMARYKEY" ),
   "CHATBOT_ID"       number not null enable annotations ( "DESCRIPTION" 'Chatbot that owns this tool.'
   ,"DISPLAY" 'Chatbot ID',"FOREIGNKEY" ),
   "TOOL_NAME"        varchar2(150 char) not null enable annotations ( "DESCRIPTION" 'Stable tool name exposed to the LLM within this chatbot, such as conversation_memory.'
   ,"DISPLAY" 'Tool Name' ),
   "DESCRIPTION"      clob not null enable
      annotations ( "DESCRIPTION" 'LLM-facing description of when and how to use this tool.',"DISPLAY" 'Description' ),
   "TOOL_TYPE"        varchar2(50 char) default on null 'CONVERSATION_MEMORY' not null enable annotations ( "DESCRIPTION" 'Internal tool executor type.'
   ,"DISPLAY" 'Tool Type' ),
   "ENABLED_YN"       varchar2(1 char) default on null 'Y' not null enable annotations ( "DESCRIPTION" 'Tool enablement flag for this chatbot.'
   ,"DISPLAY" 'Enabled' ),
   "MAX_ROWS"         number default on null 1000 not null enable annotations ( "DESCRIPTION" 'Maximum number of rows/messages the tool may inspect or return before result-size clipping.'
   ,"DISPLAY" 'Max Rows' ),
   "MAX_RESULT_CHARS" number default on null 100000 not null enable annotations ( "DESCRIPTION" 'Maximum character count returned by the tool before clipping.'
   ,"DISPLAY" 'Max Result Chars' ),
   "CREATED"          date default on null sysdate not null enable annotations ( "DESCRIPTION" 'Date when the tool definition was created.'
   ,"DISPLAY" 'Created' ),
   constraint "CB_TOOLS_ID_PK" primary key ( "ID" )
      using index enable,
   constraint "CB_TOOLS_CHATBOT_NAME_UNQ" unique ( "CHATBOT_ID",
                                                  "TOOL_NAME" )
      using index enable,
   constraint "CB_TOOLS_ENABLED_CK"
      check ( enabled_yn in ( 'Y',
                              'N' ) ) enable,
   constraint "CB_TOOLS_MAX_ROWS_CK"
      check ( max_rows > 0 ) enable,
   constraint "CB_TOOLS_MAX_RESULT_CHARS_CK"
      check ( max_result_chars > 0 ) enable
) annotations ( "DESCRIPTION" 'Stores chatbot-owned agent tool definitions exposed to LLMs.',"DISPLAY" 'Tools' );

alter table "CB_TOOLS"
   add constraint "CB_TOOLS_CHATBOT_FK"
      foreign key ( "CHATBOT_ID" )
         references "CB_CHATBOTS" ( "ID" )
         on delete cascade
      enable;

create index "CB_TOOLS_I1" on
   "CB_TOOLS" (
      "CHATBOT_ID",
      "ENABLED_YN"
   );
